Add homepage
Etsubdink-Demeke/Microverse-Hello-Microverse-project pull request #2
Opened 2023-04-25 22:53 UTC by Etsubdink-Demeke

This is a pull request for the branch add-homepage which added an index.html,style.css and test.md file to the main brach

2023-04-25 23:09 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @Etsubdink-Demeke, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

### README

- [ ] You did a great job working on your project documentation. 🚀 However, some of the required sections are empty or have boilerplate content. Please make sure to include the information about this project in the documentation! 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/234425765-cb7215d1-d465-40d7-9301-5028010bc1bb.png)

Remember that the only optional section is the FAQ one! 🤓 🔧 

### Linters

- [ ] You did a great job setting up the linters for this project, kudos for that! 🚀 However, as you can see, they flagged some errors when you pushed your code and created this pull request:

![Screenshot from 2023-04-25 18-03-36](https://user-images.githubusercontent.com/77069011/234426391-cc8aea72-2d25-4c8a-85ac-db36d826c96b.png)

You can either click on the failed checks to obtain more details and correct the errors in your code or you can set up your [linters locally](https://github.com/microverseinc/linters-config/tree/master/html-css#set-up-linters-in-your-local-env) (Highly recommended) and be notified about these errors before pushing your code for review. Please always make sure that the checks are all green (passing)! 🤓 🔧 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 01:20 UTC, didierganthier requested changes
Hi @Etsubdink-Demeke ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Well done improving the README ✔️ 
- Good job using the `.gitignore`  ✔️ 
- Correct GitHub flow was used ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- [ ] Hey 👋🏽 this is optional as it was not mentioned by the previous reviewer but make sure that the account contributing to the project is the one that is part of the Microverse org, @Etsubdink-Demeke12 is not the account you registered on Microverse with. Make sure to pay close attention to that when you commit next. The commits should come from one account 👉🏽  @Etsubdink-Demeke .

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-04-26 01:20 UTC, didierganthier commented on style.css
> +  color : black; }
Well done on the linters config but the `Stylelint` checks are still failing ❌ see below👇🏽 
![Screenshot 2023-04-25 at 21 11 35](https://user-images.githubusercontent.com/45739963/234440705-ed2f44e7-de47-4541-aade-7cd9c08d54f8.png)

The reasons and the faulty lines are mentioned below 👇🏽 
![Screenshot 2023-04-25 at 21 12 50](https://user-images.githubusercontent.com/45739963/234440866-f24c48a8-72af-431d-a39a-b21cf07e0954.png)

Make sure to adjust the `style.css` according to the requirements. 📖  Also make sure to fix the conflicts so that you're able to merge when the project is approved. ✔️

2023-04-26 02:16 UTC, didierganthier commented
@Etsubdink-Demeke do you need help on the linters?

2023-04-26 02:46 UTC, didierganthier requested changes
Hi @Etsubdink-Demeke ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Linters passing locally ✔️ 
- Implemented some required changes ✔️ 

## Required Changes 🛠
- [ ] Well done on the linters 👍🏽 they are passing locally but make sure to solve the merge conflicts that you have on GitHub so the workflow can run and the result can be green ✅ Read [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) about solving merge conflicts. ❌ 

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- N/A

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-04-26 06:47 UTC, Ibizugbe approved these changes
Hi @Etsubdink-Demeke 👋👋👋, 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] Merge conflict have been fixed and linters are passing👍.

## Optional suggestions

- [OPTIONAL] Your commit messages are descriptive👍. but for subsequent times, I recommend you always ensure they are capitalised as they give your project a more professional look.👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 06:55 UTC, merged